### ISSUE TITLE
Does not reflect newest version

### ISSUE THREAD

**Issue by topaxi** [jeffjewiss/ember-cli-postcss-import-example#1]
I tried to get this running in my current Ember.js app. My `ember-cli-build.js` looks like this:

``` js
var EmberApp = require('ember-cli/lib/broccoli/ember-app');
var autoprefixer = require('autoprefixer');
var postcssImport = require('postcss-import');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    postcssOptions: {
      compile: {
        enabled: false,
        plugins: [
          {
            module: postcssImport,
            options: {
              glob: true
            }
          }
        ]
      },
      filter: {
        enabled: true,
        plugins: [
          {
            module: autoprefixer,
            options: {
              browsers: ['last 2 version']
            }
          }
        ]
      }
    }
  });

  return app.toTree();
};
```

But I get the following if I try to build.

``` sh
topaxi $ ember build --prod
Build failed.
File: app/styles/app.css
The Broccoli Plugin: [CleanCSSFilter] failed with:
Error: Broken @import declaration of "reset.css"
Broken @import declaration of "components/my-slider.css"
Broken @import declaration of "components/my-timer.css"
Broken @import declaration of "pages/intro.css"
    at arrayToError (/home/topaxi/my-ember-app/node_modules/array-to-error/index.js:45:15)
    at minifyCallback (/home/topaxi/my-ember-app/node_modules/clean-css-promise/index.js:33:20)
    at whenSourceMapReady (/home/topaxi/my-ember-app/node_modules/clean-css/lib/clean.js:139:16)
    at Object.whenDone (/home/topaxi/my-ember-app/node_modules/clean-css/lib/clean.js:155:14)
    at processNext (/home/topaxi/my-ember-app/node_modules/clean-css/lib/imports/inliner.js:105:13)
    at importFrom (/home/topaxi/my-ember-app/node_modules/clean-css/lib/imports/inliner.js:79:10)
    at processNext (/home/topaxi/my-ember-app/node_modules/clean-css/lib/imports/inliner.js:104:16)
    at inlineLocalResource (/home/topaxi/my-ember-app/node_modules/clean-css/lib/imports/inliner.js:355:12)
    at inline (/home/topaxi/my-ember-app/node_modules/clean-css/lib/imports/inliner.js:218:10)
    at importFrom (/home/topaxi/my-ember-app/node_modules/clean-css/lib/imports/inliner.js:74:12)
    at processNext (/home/topaxi/my-ember-app/node_modules/clean-css/lib/imports/inliner.js:104:16)
    at inlineLocalResource (/home/topaxi/my-ember-app/node_modules/clean-css/lib/imports/inliner.js:355:12)
    at inline (/home/topaxi/my-ember-app/node_modules/clean-css/lib/imports/inliner.js:218:10)
    at importFrom (/home/topaxi/my-ember-app/node_modules/clean-css/lib/imports/inliner.js:74:12)
    at processNext (/home/topaxi/my-ember-app/node_modules/clean-css/lib/imports/inliner.js:104:16)
    at inlineLocalResource (/home/topaxi/my-ember-app/node_modules/clean-css/lib/imports/inliner.js:355:12)

The broccoli plugin was instantiated at: 
    at CleanCSSFilter.Plugin (/home/topaxi/my-ember-app/node_modules/broccoli-plugin/index.js:7:31)
    at CleanCSSFilter.Filter [as constructor] (/home/topaxi/my-ember-app/node_modules/broccoli-persistent-filter/index.js:60:10)
    at new CleanCSSFilter (/home/topaxi/my-ember-app/node_modules/broccoli-clean-css/index.js:17:10)
    at CleanCSSFilter (/home/topaxi/my-ember-app/node_modules/broccoli-clean-css/index.js:12:12)
    at module.exports.preprocessMinifyCss (/home/topaxi/my-ember-app/node_modules/ember-cli-preprocess-registry/preprocessors.js:116:12)
    at EmberApp.styles (/home/topaxi/my-ember-app/node_modules/ember-cli/lib/broccoli/ember-app.js:1333:26)
    at EmberApp.toArray (/home/topaxi/my-ember-app/node_modules/ember-cli/lib/broccoli/ember-app.js:1607:10)
    at EmberApp.toTree (/home/topaxi/my-ember-app/node_modules/ember-cli/lib/broccoli/ember-app.js:1628:30)
    at module.exports (/home/topaxi/my-ember-app/ember-cli-build.js:35:14)
    at CoreObject.setupBroccoliBuilder (/home/topaxi/my-ember-app/node_modules/ember-cli/lib/models/builder.js:74:19)
    at CoreObject.init (/home/topaxi/my-ember-app/node_modules/ember-cli/lib/models/builder.js:54:10)
    at CoreObject.superWrapper [as init] (/home/topaxi/my-ember-app/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.Class (/home/topaxi/my-ember-app/node_modules/core-object/core-object.js:32:33)
    at CoreObject.run (/home/topaxi/my-ember-app/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at /home/topaxi/my-ember-app/node_modules/ember-cli/lib/commands/build.js:32:24
    at tryCatch (/home/topaxi/my-ember-app/node_modules/rsvp/dist/rsvp.js:538:12)
```

**Comment by topaxi** [comment]
Haha nevermind, i got the `compile` option disabled... _facepalm_.
